apiVersion: v1
kind: Service
metadata:
  name: dbr-mysql
  labels:
    app: dbr
spec:
  ports:
    - port: 3306
  selector:
    app: dbr
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: dbr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbr-mysql
  labels:
    app: dbr
spec:
  selector:
    matchLabels:
      app: dbr
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbr
        tier: mysql
    spec:
      containers:
      - image: mariadb:10.6.4-focal
        name: mysql
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: '1'
#        - name: MYSQL_ROOT_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: mysql-pass
#              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
